language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mattdunson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mattdunson/docker-react npm run test